include:
  - proxy.yaml

x-deploy: &deploy-dev
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
      reservations:
        memory: 256M

x-env_file: &env_file
  env_file:
    - .env

x-restart: &restart
  restart: always

services:
  db:
    #image: mariadb:10.6.4-focal
    image: mysql:latest
    container_name: db
    networks:
      backend:
        ipv4_address: 172.20.0.10
    <<: [*deploy-dev, *env_file, *restart]
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_HOST="%"
    
  web:
    build:
      context: .
      dockerfile: Dockerfile.python
    image: web_app:latest
    networks:
      backend:
        ipv4_address: 172.20.0.5
    <<: [*env_file, *restart]
    environment:
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_USER=${MYSQL_USER}
      - DB_HOST=db
